### ISSUE TITLE
Feature request: Student viewed information in xls export

### ISSUE THREAD

**Issue by mike-wilson-uk** [turnitin/moodle-mod_turnitintooltwo#171]
Hi,

We've had an academic ask whether it would be possible to add whether a student has viewed a marked paper into the xls Export file. It would be really useful for this to also include the time and date the graded assignment was viewed as with the interface.

Thanks,

Mike

![screenshot from 2016-06-08 15 57 32](https://cloud.githubusercontent.com/assets/1416464/15898942/fc2f7e22-2d91-11e6-990c-c2be8ff7f541.png)

**Comment by amclarty** [comment]
@mike-wilson-uk, I've raised this with the team and will reply once we've investigated. Thanks!

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
