### ISSUE TITLE
Include en_us lang pack

### ISSUE THREAD

**Issue by rlorenzo** [turnitin/moodle-mod_turnitintooltwo#201]
We submitted a change to the en_us lang pack to rename Mark to Grade for the US lang pack.

Related to the Gradebook terminology improvements for the US lang pack, it was agreed to rename Mark/Marking to Grade/Grading.

See: https://tracker.moodle.org/browse/MDL-46175

Lang pack change, see: https://lang.moodle.org/local/amos/contrib.php?id=13822

**Comment by amclarty** [comment]
@rlorenzo, thanks for letting us know. We're currently looking at terminology for users working with Moodle and Turnitin. I'll reply once we've investigated.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
