### ISSUE TITLE
Fatal memory limit error when adding a new assignment

### ISSUE THREAD

**Issue by bedcoll-cwarwicker** [turnitin/moodle-mod_turnitintooltwo#210]
We are having a strange problem, whereby when we go to add a new Turnitin 2 assignment, on one specific course, it just sits there spinning and spinning, and eventually gives a 500 error (with debugging it's a fatal memory limit error).

I've tried increasing the memory limit, and it works fine on other courses, it's just this 1 course.

The course doesn't have any other TII assignments attached to it.

Is there anything that the module does when just trying to load up the modedit.php form to add an new instance, that would cause this memory problem?

Thanks.

**Comment by jmcgettrick** [comment]
Before creating an assignment mod_form needs to have a class in Turnitin so that the instructor can have access to shared Turnitin rubrics. This could potentially be as many as 6 API requests:

- Create/Edit Course in Turnitin
- Check if User has Turnitin account
- Create User in Turnitin
- Join the User to the Class
- Read User details
- Read Class details

Can you see anything in the API logs as to which one of those is causing a problem?
