### ISSUE TITLE
Turnitintooltwo support for Moodle Mobile (2) Remote Addons

### ISSUE THREAD

**Issue by blm-unikent** [turnitin/moodle-mod_turnitintooltwo#215]
Moodle 3.1+ offers support for mod_turnitintooltwo to develop a remote mobile addon (to the existing plugin) so that Moodle Mobile 2 users can access turnitin without resorting to a web browser.

the "How" is discussed here https://docs.moodle.org/dev/Moodle_Mobile_Remote_add-ons
1. Is this on your radar?
2. If yes, is there a roadmap or date for adding the above?

We have now developed 3 remote mobile addons for University of Kent (my employer) own resources and activities, and are keen to work with you on Turnitin.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
