### ISSUE TITLE
Response column not updating on page load

### ISSUE THREAD

**Issue by amandadoughty** [turnitin/moodle-mod_turnitintooltwo#242]
We are using Moodle 3.0.7 with TII2 v2016091401

We are finding that the response column does not show when students have viewed their feedback. If you refresh an individual submission then the response is shown.

**Comment by amclarty** [comment]
@amandadoughty,

I can't reproduce this using your Moodle and plugin versions. Once a student has viewed their marked paper if I click _Refresh Submissions_ or reload the page the viewed feedback is set correctly.

It sounds like this issue is reproducible on your end. Can you give anymore information? Is the entire column missing or the viewed icon?
