### ISSUE TITLE
Latest update v2017052401 gets undefined index as a student

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-mod_turnitintooltwo#329]
Notice: Undefined index: unit_test in /var/www/moodle/mod/turnitintooltwo/turnitintooltwo_view.class.php on line 1353

With debugging on full blast, this message would be displayed to students viewing their submission.  Might place a check there to avoid this issue.

**Comment by jmcgettrick** [comment]
Thanks @Syxton - we'll get that removed.

**Comment by matthewmarinovich** [comment]
Hi there - we have a client who has indicated that this problem is preventing some of their students from being able to properly access and submit assignments via the plugin due to this problem.  It seems that if the students have not accepted the EULA perhaps some other features are blocked?

The client has reported that they have commented out the problematic line and this fixes their other issues with the plugin.

Is there any planned target release/date for a fix for this issue?  Thanks!

**Comment by jmcgettrick** [comment]
A fix should be out soon for this - see https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/319a2eaa3125763c8b37930a20a65cb0d77e9bf7.

**Comment by dwinn** [comment]
Hi @Syxton and @matthewmarinovich ,

This has been fixed in today's release v2017070301.

**Comment by matthewmarinovich** [comment]
Awesome - thank you for letting us know.  I'll tell our client about the fix =)

Just one follow up question about the plugin: is it maintained by Turnitin or by someone else?

**Comment by dwinn** [comment]
Hi @matthewmarinovich,

The Moodle plugins are all maintained by Turnitin.

**Comment by matthewmarinovich** [comment]
Ok great - thanks!
