### ISSUE TITLE
latest build triggers unit test failures on v1migration grade category changes.

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-mod_turnitintooltwo#503]
mod_turnitintooltwo_v1migration_testcase::test_migrate_assignment
mod_turnitintooltwo_v1migration_testcase::test_migrate_multiple_submission
mod_turnitintooltwo_v1migration_testcase::test_migrate_multiple_unenrolled_users
mod_turnitintooltwo_v1migration_testcase::test_post_migration
mod_lib_testcase::test_turnitintooltwo_cron_migrate_gradebook
mod_lib_testcase::test_turnitintooltwo_cron_migrate_gradebook_1000

All fail with:
Trying to get property of non-object

/var/www/html/mod/turnitintooltwo/classes/v1migration/v1migration.php:500
/var/www/html/mod/turnitintooltwo/lib.php:724

**Comment by dwinn** [comment]
Hi @danmarsden,

Thanks for this report,

This is not good - seems we're not accounting for when a grade category doesn't exist - which it won't in the tests. I've made a small change to the develop branch and checked all the tests now pass. That will go out in the next release. Feel free to pull down this change, it is the only code change in develop since the release.

**Comment by dwinn** [comment]
Closing this as we've now released the code from develop.
