### ISSUE TITLE
Assignments not passed on cron

### ISSUE THREAD

**Issue by jerryhops** [turnitin/moodle-mod_turnitintooltwo#92]
We are having a lot of issues with assignments not being passed from Moodle to Turnitin on cron using the plagiarism plugin under mod/assign.

We do have large numbers of assignments being submitted, for example 3000 were submitted on a signle day this week, and accept there will be some latency in processing these, but four days later we have many that are stuck as "pending".

I would like to understand whether there are any known issues and how well the cron process works with large volumes of assignments (in terms of the number of assignments that can be passed on each cron run). I would add we have cron running every minute at the moment.

**Comment by jmcgettrick** [comment]
Hi Jerry, we've seen a few reports of this problem and it's due to the cron events queue for submissions being stuck. If the cron hits an event that fails then it won't process any more of that event type. 

From what we've seen, the most likely cause is that a Moodle assignment or user can't be created or edited in Turnitin therefore the event is failing, so the submission doesn't get processed.

If you have Moodle debugging enabled you should be able to see some error output in the cron. If you have Turnitin diagnostics enabled as well an error should be appearing in the API and/or activity logs.

We are hoping to release a new version in the next week that will fix this.

**Comment by jerryhops** [comment]
Thanks John, 

From what you say it seems we would have to find the issues with a given user and subsequently correct in Turnitin directly?

**Comment by jerryhops** [comment]
Also, do you know if there is a way to get it moving in the mean time, i.e. alter code to stop it failing completely?

**Comment by jmcgettrick** [comment]
With the previous cases we've tried to help diagnose the problem where possible by examining the API and Activity logs, which has got things moving. As for code changes, it's not just a single line fix so it would need a fair amount of altering.

Can you attach logs here and I'll take a look? Or you could contact support and we'll take a look.

**Comment by jmcgettrick** [comment]
We have released 2016011101 which should fix this issue in most cases.

**Comment by jerryhops** [comment]
Thats great, thanks.
